config/routes.rb
Materialsys::Application.routes.draw do
	resource  :session
	match '/login' => "sessions#new", :as => "login" 
	match '/logout' => "sessions#destroy", :as => "logout"
	match 'code/importcode' => 'code#importcode'
	match 'manager/outportmaterial' => 'manager#outportmaterial'
	match 'manager/importmaterial' => 'manager#importmaterial'
	match "supplier/importsupplier"=>"supplier#importsupplier"
	match 'user/edit'=>"user#edit"
	match 'user/data'=>"user#data"
	match 'user/add'=>"user#add"

	match "bom/download1"=>"bom#download1"
	match "bom/download2"=>"bom#download2"
	match "bom/download"=>"bom#download"
	match "bom/list"=>"bom#list"
    get "project/list"
	match "code/ajax"=>"code#ajax"
	match "code/list"=>"code#list"
	match "manager/all"=>"manager#all"
	match "manager/download"=>"manager#download"
	match "sample/upload"=>"sample#upload"
	match "supplier/list"=>"supplier#list"

   root :to => 'home#index'

   match ':controller(/:action(/:id))(.:format)'
end

app/views/layouts/_footer.html.erb
<div id="system_info"> 
        当前操作系统： <span id="platform"></span>&nbsp;&nbsp;&nbsp;&nbsp;
        浏览器： <span id="broswer"></span>&nbsp;&nbsp;&nbsp;&nbsp;
</div>

app/views/layouts/_header.html.erb
<div id="login-info">
  <span id="result"></span>
   &nbsp;&nbsp;&nbsp;&nbsp;
  <span>欢迎您，<%= User.find(session[:user_id]).username %></span>
  <span class="color-gray">|</span>
<%= link_to t('sign_out'),logout_path %>
</div>


app/views/layouts/_menu.html.erb
<ul>

  <li id="repo-management" class="left-menu">
     <%= link_to manager_importmaterial_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">入库管理</div>
     <% end %>
     
     <%= link_to manager_outportmaterial_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">出库管理</div>
     <% end %>
     
     
     
     <%= link_to manager_all_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_11.png", :class=>'menu-icon') %></div>
     <div class="menu-text">库存管理</div>
     <% end %>
  </li>
  


  <li id="tree" class="left-menu">
     <%= link_to code_importcode_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">编码导入</div>
     <% end %>
  </li>

  <li id="suppliertree" class="left-menu">
     <%= link_to supplier_list_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_13.png", :class=>'menu-icon') %></div>
     <div class="menu-text">供应商查看</div>
     <% end %>
     <%= link_to supplier_importsupplier_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">供应商导入</div>
     <% end %>
  </li>
   
  <li id="bom-management" class="left-menu">
     <%= link_to project_list_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_13.png", :class=>'menu-icon') %></div>
     <div class="menu-text">项目查看</div>
     <% end %>
    
  </li>

  <li id="user-management" class="left-menu">
    <%= link_to user_edit_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">修改密码</div>
     <% end %>
    <%= link_to user_data_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">修改资料</div>
     <% end %>
     <% if current_user.role == 'root' %>
      <%= link_to user_add_path(:format=>:js), :remote=>true do %>
     <div><%= image_tag("shortcuts_12.png", :class=>'menu-icon') %></div>
     <div class="menu-text">添加用户</div>
     <% end %>
     <% end %>
  </li>
  
   
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t(:materialsys) %></title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<style>
#home-page {
	background: #DCDDDF url(assets/blue.jpg);
}
</style>
<body onload=window_onload()>
<div id="header">
  <%= render :partial => "layouts/header" %>
</div>
<div id="menu">
  <%= render :partial => "layouts/menu" %>
</div>
<div id="footer">
  <%= render :partial => "layouts/footer" %>
</div>
<div id="home-page">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title><%= t(:materialsys) %></title>
<%= stylesheet_link_tag    "application.css" %>
<%= csrf_meta_tags %>
<style>
/* Reset CSS */
html, body, div, span, applet, object, iframe,
h1, h2, h3, h4, h5, h6, p, blockquote, pre,
a, abbr, acronym, address, big, cite, code,
del, dfn, em, font, img, ins, kbd, q, s, samp,
small, strike, strong, sub, sup, tt, var,
b, u, i, center,
dl, dt, dd, ol, ul, li,
fieldset, form, label, legend,
table, caption, tbody, tfoot, thead, tr, th, td {
	margin: 0;
	padding: 0;
	border: 0;
	outline: 0;
	font-size: 100%;
	vertical-align: baseline;
	background: transparent;
}
body {
 
	background: #DCDDDF url(assets/blue.jpg);
	color: #000;
	font: 14px Arial;
	margin: 0 auto;
	padding: 0;
	position: relative;
}
h1{ font-size:28px;}
h2{ font-size:26px;}
h3{ font-size:18px;}
h4{ font-size:16px;}
h5{ font-size:14px;}
h6{ font-size:12px;}
h1,h2,h3,h4,h5,h6{ color:#563D64;}
small{ font-size:10px;}
b, strong{ font-weight:bold;}
a{ text-decoration: none; }
a:hover{ text-decoration: underline; }
</style>
</head>

<body>
<div class="container">
	<section id="content">
		<%= form_tag session_path do %> 
			<h1><%= t('login form') %></h1>
			<div>
				<%= text_field_tag :username, nil, :id=>'username', :placeholder=>t('username')  %>
                                
			</div>
			<div>
				<%= password_field_tag :password, nil, :id=>'password', :placeholder=>t('enterpassword') %>
                                
			</div>
                        
			<div>
				<input type="submit" value=<%= t('login') %> /> 
			</div>
		<% end %>  
	</section><!-- content -->
</div><!-- container -->

</body>
</html>